Header header

# Drive command
uint8 CMD_NONE=0
uint8 CMD_DRIVE=1
uint8 CMD_TURN=2
uint8 CMD_SADL=3
uint8 CMD_KILL=4
uint8 cmd

# Command direction
uint8 DIR_LEFT=0
uint8 DIR_UP=0
uint8 DIR_FORWARD=0
uint8 DIR_RIGHT=1
uint8 DIR_DOWN=1
uint8 DIR_BACKWARD=1
uint8 DIR_AUTOLEVEL=2
uint8 dir

# Command unit
uint8 UNIT_SECONDS=0
uint8 UNIT_ROTATIONS=1
uint8 UNIT_DEGREES=2
uint8 UNIT_METERS=3
uint8 unit

# Command value
float32 value

# Command throttle
float32 throttle

